name: Update MGNREGA Full List

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download MGNREGA Government List
        run: |
          curl -L --fail --retry 3 \
          "https://mnregaweb2.dord.gov.in/Netnrega/writereaddata/citizen_out/panchregpeople_1816002028_local2627.html" \
          -o data.html

      - name: Save Full List
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data.html

          if git diff --cached --quiet; then
            echo "No changes found"
          else
            git commit -m "Update MGNREGA full list"
            git push
          fi
